# Generated by Django 5.0.6 on 2024-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=100)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de la noticia', null=True, upload_to='noticias/')),
                ('resena', models.TextField(blank=True, help_text='Breve reseña del contenido de la noticia')),
                ('cuerpo', models.TextField(help_text='Cuerpo de la noticia')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de publicación de la noticia')),
                ('visitas', models.PositiveIntegerField(default=0, help_text='Número de visitas a la noticia')),
            ],
        ),
    ]
