# Generated by Django 5.0.6 on 2024-07-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del juego', max_length=50)),
                ('clasificacion', models.CharField(choices=[('PEGI 3', 'Apto para todas las edades'), ('PEGI 7', 'Adecuado para niños pequeños'), ('PEGI 12', 'Apto para niños mayores de 12 años'), ('PEGI 16', 'Apto para niños mayores de 16 años'), ('PEGI 18', 'Solo apto para adultos')], help_text='Clasificación del juego', max_length=40)),
                ('resena', models.TextField(blank=True, help_text='Breve reseña del contenido del juego')),
                ('puntaje_metacritic', models.PositiveIntegerField(help_text='Valor del juego')),
                ('fecha_lanzamiento', models.DateField(help_text='Fecha de la publicacion del juego')),
            ],
        ),
    ]
