# Generated by Django 5.0.6 on 2024-07-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='fecha_lanzamiento',
            field=models.DateField(help_text='Fecha de la publicación del juego'),
        ),
    ]
