# Generated by Django 5.0.6 on 2024-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='games/'),
        ),
    ]
